### ISSUE TITLE
试过scheme-lib作为环境么？

### ISSUE THREAD

**Issue by evilbinary** [jiacai2050/sicp#15]
试过scheme lib 么 [https://github.com/scheme-lib/scheme-lib](https://github.com/scheme-lib/scheme-lib)

**Comment by jiacai2050** [comment]
和这本书好想没什么关系。

**Comment by evilbinary** [comment]
@jiacai2050 想用你这个作为scheme lib的教程，怎么样？

**Comment by jiacai2050** [comment]
scheme lib 看上去是画图用的，和 sicp 关系不大。如果你觉得有需要，代码是 MIT 的。

**Comment by evilbinary** [comment]
@jiacai2050 不仅仅画图，主要是写后台服务器用的。
