### ISSUE TITLE
3.31

### ISSUE THREAD

**Issue by koallen** [jiacai2050/sicp#8]
你好，参考了你3.31习题的解答。这里想探讨一下。

我觉得你对half adder例子中inverter的分析是对的，不过加`(proc)`的原因我觉得措辞可以改一下。原因准确说不应该是让input不变的时候改变output，而是**初始化**的时候确保output会有正确的值。这里有一个初始化的限定，因为`after-delay`只是被调用了一次而已。

**Comment by jiacai2050** [comment]
你好，抱歉这么久才回复。

你的解释应该更准确些，我已经更新了3.31，你可以再看看。

https://github.com/jiacai2050/sicp/blob/master/exercises/03/3.31.md
